#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define NOTOEMOJI_10_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notoemoji_10_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define NOTOEMOJI_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notoemoji_12_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define NOTOEMOJI_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notoemoji_14_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define NOTOEMOJI_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notoemoji_16_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define NOTOSYMBOLS_10_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notosymbols_10_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define NOTOSYMBOLS_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notosymbols_12_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define NOTOSYMBOLS_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notosymbols_14_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define NOTOSYMBOLS_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notosymbols_16_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define LEXENDDECA_10_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_10_regular.h",\
  "./lexenddeca_10_bold.h",\
  "./lexenddeca_10_bolditalic.h",\
  "./lexenddeca_10_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define LEXENDDECA_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_12_regular.h",\
  "./lexenddeca_12_bold.h",\
  "./lexenddeca_12_bolditalic.h",\
  "./lexenddeca_12_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define LEXENDDECA_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_14_regular.h",\
  "./lexenddeca_14_bold.h",\
  "./lexenddeca_14_bolditalic.h",\
  "./lexenddeca_14_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define LEXENDDECA_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_16_regular.h",\
  "./lexenddeca_16_bold.h",\
  "./lexenddeca_16_bolditalic.h",\
  "./lexenddeca_16_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_10_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_10_regular.h",\
  "./charein_10_bold.h",\
  "./charein_10_bolditalic.h",\
  "./charein_10_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_12_regular.h",\
  "./charein_12_bold.h",\
  "./charein_12_bolditalic.h",\
  "./charein_12_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_14_regular.h",\
  "./charein_14_bold.h",\
  "./charein_14_bolditalic.h",\
  "./charein_14_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_16_regular.h",\
  "./charein_16_bold.h",\
  "./charein_16_bolditalic.h",\
  "./charein_16_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define BITTER_10_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./bitter_10_regular.h",\
  "./bitter_10_bold.h",\
  "./bitter_10_bolditalic.h",\
  "./bitter_10_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define BITTER_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./bitter_12_regular.h",\
  "./bitter_12_bold.h",\
  "./bitter_12_bolditalic.h",\
  "./bitter_12_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define BITTER_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./bitter_14_regular.h",\
  "./bitter_14_bold.h",\
  "./bitter_14_bolditalic.h",\
  "./bitter_14_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define BITTER_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./bitter_16_regular.h",\
  "./bitter_16_bold.h",\
  "./bitter_16_bolditalic.h",\
  "./bitter_16_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define UI_10_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./ubuntu_10_regular.h",\
  "./ubuntu_10_bold.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define UI_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./ubuntu_12_regular.h",\
  "./ubuntu_12_bold.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define SMALL_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./inter_8_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"
