#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define LEXENDDECA_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_12_regular.h",\
  "./lexenddeca_12_bold.h",\
  "./lexenddeca_12_bolditalic.h",\
  "./lexenddeca_12_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define LEXENDDECA_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_14_regular.h",\
  "./lexenddeca_14_bold.h",\
  "./lexenddeca_14_bolditalic.h",\
  "./lexenddeca_14_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define LEXENDDECA_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_16_regular.h",\
  "./lexenddeca_16_bold.h",\
  "./lexenddeca_16_bolditalic.h",\
  "./lexenddeca_16_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define LEXENDDECA_18_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./lexenddeca_18_regular.h",\
  "./lexenddeca_18_bold.h",\
  "./lexenddeca_18_bolditalic.h",\
  "./lexenddeca_18_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_12_regular.h",\
  "./charein_12_bold.h",\
  "./charein_12_bolditalic.h",\
  "./charein_12_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_14_regular.h",\
  "./charein_14_bold.h",\
  "./charein_14_bolditalic.h",\
  "./charein_14_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_16_regular.h",\
  "./charein_16_bold.h",\
  "./charein_16_bolditalic.h",\
  "./charein_16_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define CHAREINK_18_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./charein_18_regular.h",\
  "./charein_18_bold.h",\
  "./charein_18_bolditalic.h",\
  "./charein_18_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define ATKINSONHL_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./atkinsonhl_12_regular.h",\
  "./atkinsonhl_12_bold.h",\
  "./atkinsonhl_12_bolditalic.h",\
  "./atkinsonhl_12_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define ATKINSONHL_14_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./atkinsonhl_14_regular.h",\
  "./atkinsonhl_14_bold.h",\
  "./atkinsonhl_14_bolditalic.h",\
  "./atkinsonhl_14_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define ATKINSONHL_16_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./atkinsonhl_16_regular.h",\
  "./atkinsonhl_16_bold.h",\
  "./atkinsonhl_16_bolditalic.h",\
  "./atkinsonhl_16_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define ATKINSONHL_18_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./atkinsonhl_18_regular.h",\
  "./atkinsonhl_18_bold.h",\
  "./atkinsonhl_18_bolditalic.h",\
  "./atkinsonhl_18_italic.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define UI_10_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./ubuntu_10_regular.h",\
  "./ubuntu_10_bold.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define UI_12_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./ubuntu_12_regular.h",\
  "./ubuntu_12_bold.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"

echo "#define SMALL_FONT_ID ($(\
ruby -rdigest -e 'puts [\
  "./notosans_8_regular.h",\
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'\
))"
