#pragma once

#ifndef OMIT_CHAREINK_FONT
#include <builtinFonts/charein_10_bold.h>
#include <builtinFonts/charein_10_bolditalic.h>
#include <builtinFonts/charein_10_italic.h>
#include <builtinFonts/charein_10_regular.h>
#include <builtinFonts/charein_12_bold.h>
#include <builtinFonts/charein_12_bolditalic.h>
#include <builtinFonts/charein_12_italic.h>
#include <builtinFonts/charein_12_regular.h>
#include <builtinFonts/charein_14_bold.h>
#include <builtinFonts/charein_14_bolditalic.h>
#include <builtinFonts/charein_14_italic.h>
#include <builtinFonts/charein_14_regular.h>
#include <builtinFonts/charein_16_bold.h>
#include <builtinFonts/charein_16_bolditalic.h>
#include <builtinFonts/charein_16_italic.h>
#include <builtinFonts/charein_16_regular.h>
#endif  // OMIT_CHAREINK_FONT
#include <builtinFonts/lexenddeca_10_bold.h>
#include <builtinFonts/lexenddeca_10_bolditalic.h>
#include <builtinFonts/lexenddeca_10_italic.h>
#include <builtinFonts/lexenddeca_10_regular.h>
#include <builtinFonts/lexenddeca_12_bold.h>
#include <builtinFonts/lexenddeca_12_bolditalic.h>
#include <builtinFonts/lexenddeca_12_italic.h>
#include <builtinFonts/lexenddeca_12_regular.h>
#include <builtinFonts/lexenddeca_14_bold.h>
#include <builtinFonts/lexenddeca_14_bolditalic.h>
#include <builtinFonts/lexenddeca_14_italic.h>
#include <builtinFonts/lexenddeca_14_regular.h>
#include <builtinFonts/lexenddeca_16_bold.h>
#include <builtinFonts/lexenddeca_16_bolditalic.h>
#include <builtinFonts/lexenddeca_16_italic.h>
#include <builtinFonts/lexenddeca_16_regular.h>
#include <builtinFonts/inter_8_regular.h>
#include <builtinFonts/dmsans_10_bold.h>
#include <builtinFonts/dmsans_10_regular.h>
#include <builtinFonts/dmsans_12_bold.h>
#include <builtinFonts/dmsans_12_regular.h>
#include <builtinFonts/bitter_10_bold.h>
#include <builtinFonts/bitter_10_bolditalic.h>
#include <builtinFonts/bitter_10_italic.h>
#include <builtinFonts/bitter_10_regular.h>
#include <builtinFonts/bitter_12_bold.h>
#include <builtinFonts/bitter_12_bolditalic.h>
#include <builtinFonts/bitter_12_italic.h>
#include <builtinFonts/bitter_12_regular.h>
#include <builtinFonts/bitter_14_bold.h>
#include <builtinFonts/bitter_14_bolditalic.h>
#include <builtinFonts/bitter_14_italic.h>
#include <builtinFonts/bitter_14_regular.h>
#include <builtinFonts/bitter_16_bold.h>
#include <builtinFonts/bitter_16_bolditalic.h>
#include <builtinFonts/bitter_16_italic.h>
#include <builtinFonts/bitter_16_regular.h>