#pragma once

#include <builtinFonts/atkinsonhl_12_bold.h>
#include <builtinFonts/atkinsonhl_12_bolditalic.h>
#include <builtinFonts/atkinsonhl_12_italic.h>
#include <builtinFonts/atkinsonhl_12_regular.h>
#include <builtinFonts/atkinsonhl_14_bold.h>
#include <builtinFonts/atkinsonhl_14_bolditalic.h>
#include <builtinFonts/atkinsonhl_14_italic.h>
#include <builtinFonts/atkinsonhl_14_regular.h>
#include <builtinFonts/atkinsonhl_16_bold.h>
#include <builtinFonts/atkinsonhl_16_bolditalic.h>
#include <builtinFonts/atkinsonhl_16_italic.h>
#include <builtinFonts/atkinsonhl_16_regular.h>
#include <builtinFonts/atkinsonhl_18_bold.h>
#include <builtinFonts/atkinsonhl_18_bolditalic.h>
#include <builtinFonts/atkinsonhl_18_italic.h>
#include <builtinFonts/atkinsonhl_18_regular.h>
#include <builtinFonts/charein_12_bold.h>
#include <builtinFonts/charein_12_bolditalic.h>
#include <builtinFonts/charein_12_italic.h>
#include <builtinFonts/charein_12_regular.h>
#include <builtinFonts/charein_14_bold.h>
#include <builtinFonts/charein_14_bolditalic.h>
#include <builtinFonts/charein_14_italic.h>
#include <builtinFonts/charein_14_regular.h>
#include <builtinFonts/charein_16_bold.h>
#include <builtinFonts/charein_16_bolditalic.h>
#include <builtinFonts/charein_16_italic.h>
#include <builtinFonts/charein_16_regular.h>
#include <builtinFonts/charein_18_bold.h>
#include <builtinFonts/charein_18_bolditalic.h>
#include <builtinFonts/charein_18_italic.h>
#include <builtinFonts/charein_18_regular.h>
#include <builtinFonts/lexenddeca_12_bold.h>
#include <builtinFonts/lexenddeca_12_bolditalic.h>
#include <builtinFonts/lexenddeca_12_italic.h>
#include <builtinFonts/lexenddeca_12_regular.h>
#include <builtinFonts/lexenddeca_14_bold.h>
#include <builtinFonts/lexenddeca_14_bolditalic.h>
#include <builtinFonts/lexenddeca_14_italic.h>
#include <builtinFonts/lexenddeca_14_regular.h>
#include <builtinFonts/lexenddeca_16_bold.h>
#include <builtinFonts/lexenddeca_16_bolditalic.h>
#include <builtinFonts/lexenddeca_16_italic.h>
#include <builtinFonts/lexenddeca_16_regular.h>
#include <builtinFonts/lexenddeca_18_bold.h>
#include <builtinFonts/lexenddeca_18_bolditalic.h>
#include <builtinFonts/lexenddeca_18_italic.h>
#include <builtinFonts/lexenddeca_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
