name: Compile Release Candidate

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-release-candidate:
    if: startsWith(github.ref_name, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('platformio.ini', 'platformio.local.example.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Install PlatformIO Core
        run: uv pip install --system -U https://github.com/pioarduino/platformio-core/archive/refs/tags/v6.1.19.zip

      - name: Set version from branch
        run: |
          VERSION="${GITHUB_REF_NAME#release/}-RC"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          sed -i "s/crossink_version = .*/crossink_version = $VERSION/" platformio.ini

      - name: Build CrossPoint
        run: pio run -e tiny -e xlarge -e no_emoji

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CrossPoint-RC-${{ env.VERSION }}
          path: |
            .pio/build/tiny/firmware-tiny.bin
            .pio/build/xlarge/firmware-xlarge.bin
            .pio/build/no_emoji/firmware-no_emoji.bin
